#The latest supported version of Postgres for Flyway is 15
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/hibernate
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: public
            connection-timeout: 20000
            minimum-idle: 2
    flyway:
        baseline-on-migrate: true
        enabled: true
        user: postgres
        password: postgres
        baseline-description: "init"
        baseline-version: 0
        locations: classpath:db/migration
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true